# Generated by Django 3.1.7 on 2021-03-13 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=5000)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('img', models.ImageField(upload_to='images/blogImg')),
            ],
        ),
    ]
