# Generated by Django 3.1.7 on 2021-03-14 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=5000)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
    ]
