# Generated by Django 3.1.7 on 2021-03-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='NO email', max_length=50),
        ),
    ]
