# Generated by Django 3.1.7 on 2021-03-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0004_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
