# Generated by Django 3.1.7 on 2021-03-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0005_auto_20210315_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=models.TextField(max_length=5000),
        ),
    ]
