# Generated by Django 3.1.7 on 2021-03-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0006_auto_20210315_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Mdesc',
            field=models.TextField(default='  ', max_length=5000),
        ),
    ]
