# Generated by Django 3.1.7 on 2021-03-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0007_blogs_mdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='ExtraMoredesc',
            field=models.TextField(default='  ', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogs',
            name='Extradesc',
            field=models.TextField(default='  ', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogs',
            name='MMdesc',
            field=models.TextField(default='  ', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogs',
            name='Moredesc',
            field=models.TextField(default='  ', max_length=5000),
        ),
    ]
