# Generated by Django 3.1.7 on 2021-03-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0008_auto_20210315_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='ExtraMoredesc',
            field=models.TextField(default='  Empty', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Extradesc',
            field=models.TextField(default='  Empty', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='MMdesc',
            field=models.TextField(default='Empty', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Mdesc',
            field=models.TextField(default=' Empty ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Moredesc',
            field=models.TextField(default=' Empty ', max_length=5000),
        ),
    ]
