# Generated by Django 3.1.7 on 2021-03-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0009_auto_20210315_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='ExtraMoredesc',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='Extradesc',
        ),
    ]
