# Generated by Django 3.1.7 on 2021-03-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0010_auto_20210316_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='MMdesctitle',
            field=models.CharField(default='Empty', max_length=50),
        ),
        migrations.AddField(
            model_name='blogs',
            name='Mdesctitle',
            field=models.CharField(default='Empty', max_length=50),
        ),
        migrations.AddField(
            model_name='blogs',
            name='Moredesctitle',
            field=models.CharField(default='Empty', max_length=50),
        ),
    ]
