# Generated by Django 3.1.7 on 2021-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0011_auto_20210316_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Mdesc',
            field=models.TextField(default='Empty', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Moredesc',
            field=models.TextField(default=' Empty', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.CharField(default='No category', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=models.TextField(default='No desc', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(default='No title', max_length=50),
        ),
    ]
