# Generated by Django 3.1.7 on 2021-03-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0012_auto_20210316_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='MMdescimg',
            field=models.ImageField(default='TechBlog\\static\\img\\default.png', upload_to='images/blogImg'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='Mdescimg',
            field=models.ImageField(default='TechBlog\\static\\img\\default.png', upload_to='images/blogImg'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='Moredescimg',
            field=models.ImageField(default='TechBlog\\static\\img\\default.png', upload_to='images/blogImg'),
        ),
    ]
