# Generated by Django 3.1.7 on 2021-03-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0013_auto_20210316_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='carouselimg1',
            field=models.ImageField(default='TechBlog\\static\\img\\default.png', upload_to='images/blogImg'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='carouselimg2',
            field=models.ImageField(default='TechBlog\\static\\img\\default.png', upload_to='images/blogImg'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='carouselimg3',
            field=models.ImageField(default='TechBlog\\static\\img\\default.png', upload_to='images/blogImg'),
        ),
    ]
