# Generated by Django 3.1.7 on 2021-03-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0014_auto_20210316_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carosel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carouselimg1', models.ImageField(default='TechBlog\\static\\img\\default.png', upload_to='images/blogImg')),
                ('carouselimg2', models.ImageField(default='TechBlog\\static\\img\\default.png', upload_to='images/blogImg')),
                ('carouselimg3', models.ImageField(default='TechBlog\\static\\img\\default.png', upload_to='images/blogImg')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='carouselimg1',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='carouselimg2',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='carouselimg3',
        ),
    ]
