# Generated by Django 3.1.7 on 2021-03-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0015_auto_20210316_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='MMdesctitle',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Mdesctitle',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Moredesctitle',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(default='No title', max_length=200),
        ),
    ]
