# Generated by Django 3.1.7 on 2021-03-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechWorld', '0016_auto_20210317_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='MMdesc',
            field=models.TextField(default='Empty', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Mdesc',
            field=models.TextField(default='Empty', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Moredesc',
            field=models.TextField(default=' Empty', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=models.TextField(default='No desc', max_length=1000),
        ),
    ]
